# Generated by Django 3.1.4 on 2021-01-19 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=250)),
                ('content', models.CharField(default='content', max_length=250)),
                ('complete', models.BooleanField(default=False)),
                ('status', models.CharField(default='Incomplete', max_length=25)),
                ('category', models.CharField(default='category', max_length=10)),
                ('created', models.DateField(default=datetime.datetime(2021, 1, 19, 7, 46, 40, 89554, tzinfo=utc))),
                ('due_date', models.DateField(default=datetime.datetime(2021, 1, 19, 7, 46, 40, 89554, tzinfo=utc))),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
